WITH RANK_DATA AS(
    SELECT ID, PERCENT_RANK() OVER(
        ORDER BY SIZE_OF_COLONY DESC
    ) AS SIZE_DATA
    FROM ECOLI_DATA
)

SELECT ID, 
        CASE
            WHEN SIZE_DATA <=0.25 THEN 'CRITICAL'
            WHEN SIZE_DATA <=0.50 THEN 'HIGH'
            WHEN SIZE_DATA <=0.75 THEN 'MEDIUM'
            ELSE 'LOW'
        END AS 'COLONY_NAME'
FROM RANK_DATA
ORDER BY 1 ASC;