WITH RECURSIVE GenerationCTE AS(
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, G.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA E JOIN GenerationCTE G
    ON E.PARENT_ID = G.ID
),
LeafNodes AS (
    SELECT G.ID AS ID, G.GENERATION AS GENERATION
    FROM GenerationCTE G
    LEFT JOIN ECOLI_DATA E
    ON G.ID = E.PARENT_ID
    WHERE E.ID IS NULL   
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM LeafNodes
GROUP BY GENERATION
ORDER BY 2;

