SELECT CATEGORY, FP.PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT FP
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    AND FP.PRICE = (SELECT MAX(PRICE)
                   FROM FOOD_PRODUCT
                   WHERE FP.CATEGORY = CATEGORY)
ORDER BY 2 DESC;