WITH DEVELOPERS_SKILLS AS (
    SELECT 
        D.ID AS ID,
        D.EMAIL AS EMAIL,
        S.CATEGORY AS CATEGORY,
        S.NAME AS SKILL_NAME
    FROM DEVELOPERS D
    JOIN SKILLCODES S
    ON D.SKILL_CODE & S.CODE > 0
),
GRADED_DEVELOPERS AS (
    SELECT 
        ID,
        EMAIL,
        CASE 
            WHEN SUM(CASE WHEN CATEGORY = 'Front End' THEN 1 ELSE 0 END) > 0 AND SUM(CASE WHEN SKILL_NAME = 'Python' THEN 1 ELSE 0 END) > 0 THEN 'A'
            WHEN SUM(CASE WHEN SKILL_NAME = 'C#' THEN 1 ELSE 0 END) THEN 'B'
            WHEN SUM(CASE WHEN CATEGORY = 'Front End' THEN 1 ELSE 0 END) > 0 THEN 'C'
            ELSE NULL
        END AS GRADE
    FROM DEVELOPERS_SKILLS
    GROUP BY ID, EMAIL
)

SELECT GRADE, ID, EMAIL
FROM GRADED_DEVELOPERS
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID;